import express from 'express';
import { OpenAIService } from './OpenAIService';
import type { ChatCompletionMessageParam, ChatCompletionChunk } from "openai/resources/chat/completions";
import type OpenAI from 'openai';
import util from 'util';
import { load } from 'cheerio';
import { exec } from 'child_process';
import axios from 'axios';
import { useInstructionPrompt } from './prompts';

/*
Start Express server
*/
const execAsync = util.promisify(exec);

const app = express();
const port = 3000;
app.use(express.json());
app.listen(port, () => console.log(`Server running at http://localhost:${port}. Listening for POST /api/chat requests`));

const openaiService = new OpenAIService();
let previousSummarization = "";



// Function to create system prompt
function createSystemPrompt(summarization: string): ChatCompletionMessageParam {
  return { 
    role: "system", 
    content: `You are Alice, a helpful assistant who speaks using as few words as possible. 

    ${summarization ? `Here is a summary of the conversation so far: 
    <conversation_summary>
      ${summarization}
    </conversation_summary>` : ''} 
    
    Let's chat!` 
  };
};

const API_URL = 'https://xyz.ag3nts.org/verify';

//interface
interface MessagePayload {
  msgID: number;
  text: string;
}




// Hack https://xyz.ag3nts.org/
app.post('/hackxyz', async (req, res) => {
  try {

    const readyResponse = await axios.post<MessagePayload>(API_URL, {
      text: 'READY',
      msgID: 0
    }, {
      headers: {
        'accept': 'application/json',
        'Content-Type': 'application/json'
      }
    });

    const { msgID, text } = readyResponse.data;

    if (!text || !msgID) {
      console.warn('No message received.');
      return;
    }

    console.log(`Received: ${text}`);

    // Step 2: Use LLM to answer the question
    const systemPrompt = createSystemPrompt(useInstructionPrompt);
    const userMessage: ChatCompletionMessageParam = { role: 'user', content: text };

    let assistantResponse = await openaiService.completion(
      [systemPrompt, userMessage],
      'gpt-4o',
      false
    ) as OpenAI.Chat.Completions.ChatCompletion;

    let answer = assistantResponse.choices[0]?.message?.content?.trim();

    if (!answer) {
      console.error('No answer generated by LLM.');
      return;
    }

    console.log(`Answer: ${answer}`);

    // Step 3: Send the answer back with msgID
    const submitResponse = await axios.post(API_URL, {
      text: answer,
      msgID
    }, {
      headers: {
        'accept': 'application/json',
        'Content-Type': 'application/json'
      }
    });

    console.log('Submission response:', submitResponse.data);

  } catch (error) {
    console.error('Error handling question:', error);
  }
})